name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-26

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Integrated packaging environment (packages)
        run: brew install packages

      - name: Build KhmerUnicode.bundle
        run: make build

      - name: Build Khmer Unicode.pkg
        run: make installer

      # if a release is being created, upload the package to the release
      - name: Upload releases
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
